### ISSUE TITLE
Organise addons/sourcemod/scripting/ into better sub-directories.

### ISSUE THREAD

**Issue by zonical** [CreatorsTF/gameservers#15]
Currently, the `addons/sourcemod/scripting` folder is a massive mess of unorganized files with folders barely being utilized. This is troubling as these plugins have a lot of different purposes, but it's hard to tell what's needed for a certain purpose (e.g Creators.TF Economy).

For the economy at least, I reckon that all `cecon_` files, `tf_persist_item`, `tf2_attributes`, and `tf2wearables` be put into a new folder called `/economy/`, with `/attributes` being moved into this folder as well.

This shouldn't affect compiling, but it's just a nice QOL change for people working on SourcePawn files.

**Comment by sapphonie** [comment]
Closed b484af3a6659afef0137c5a2e64dae5644974122
