### ISSUE TITLE
Brick will keep bleeding effect on player after being hit by their own airblasted brick

### ISSUE THREAD

**Issue by KayaDLX** [CreatorsTF/gameservers#19]
Title, reported by MefistofelL on the Creators.TF Discord.

Apparently you will keep the bleeding effect if the brick is deflected at you, and this until you take a medipack.

![image](https://user-images.githubusercontent.com/67245359/131988271-b52c6e4a-cf72-417e-b0e1-e0fd7df59a4b.png)

**Comment by zonical** [comment]
The problem has been fixed in a recent merge request to the servers. The plugin should be reloaded already or if not, by the next map change.
