### ISSUE TITLE
Cosmetics being disabled on join not clear to users

### ISSUE THREAD

**Issue by TheSpookiestUser** [CreatorsTF/gameservers#22]
When joining a C.TF server, all cosmetics are turned off by default.  This happens regardless of whether the user previously enabled cosmetics or not.  This problem is really twofold:

1. There should be some indication to players that cosmetics need to be enabled, something prominent
2. A user's preference of having cosmetics on should be saved between play sessions

**Comment by sapphonie** [comment]
Can not repro 2

**Comment by sapphonie** [comment]
43cacf450da546db7a9cc22188eb85cc39036b3e
