### ISSUE TITLE
Custom cosmetics appear in ragdolls even with custom cosmetics disabled

### ISSUE THREAD

**Issue by BernardoGomesNegri** [CreatorsTF/gameservers#28]
If you disable custom cosmetics using the /ctfhats, custom cosmetics will not show up on players. However, the game still tries to make custom cosmetics show on ragdolls, even with custom cosmetics disabled, which means that if you don't have the full asset pack, will result in the error model appearing. The error model is quite distracting and can sometimes block vision in tight chokepoints. I am sure I disabled custom cosmetics.
Some screenshots of this happening, note that on the last screenshot, it even says that I disabled custom cosmetics:

https://steamcommunity.com/sharedfiles/filedetails/?id=2601243889
https://steamcommunity.com/sharedfiles/filedetails/?id=2601243859
https://steamcommunity.com/sharedfiles/filedetails/?id=2601243831

**Comment by sapphonie** [comment]
dup of #25
