### ISSUE TITLE
Daily server restarts on EU servers occur at 11:00 GMT, when the server may be active

### ISSUE THREAD

**Issue by eedefeed** [CreatorsTF/gameservers#29]
I think the EU server restart timer should be adjusted to take place at something like 4:00am GMT. I feel like fewer people are playing at that time than at 11:00am. Maybe you could look through server statistics and find the time when the fewest people are playing?

A few times I've been playing at 11:00am and there's maybe 7 people on each side. After the daily restart that goes back down to 3 or 4 per side, due to the long restart time. You might find that restarting the server at a different time gives the server more momentum going into peak hours.

**Comment by sapphonie** [comment]
Good idea, will implement

**Comment by sapphonie** [comment]
Closed in fff6e6aa164ae7ebef14c75f630030dc7093f0d2
