### ISSUE TITLE
steam://connect/ does not work for east coast servers

### ISSUE THREAD

**Issue by digivee** [CreatorsTF/gameservers#32]
East coast servers dont work using steam://connect/
Gives the message "Server is not responding"
![image](https://user-images.githubusercontent.com/14162763/134432920-5fa3d346-ca0b-4a60-9a92-44592a6bbfaf.png)

**Comment by sapphonie** [comment]
Valve broke multihomed servers' connection to the Steam Master Server in the recent (9/17/21) update. This is out of our control until that is fixed.

**Comment by sapphonie** [comment]
Resolved with `STEAM_GAMESERVER_A2S_INFO_STRICT_LEGACY_PROTOCOL=1` and `-websocket` in startup cmdline
