### ISSUE TITLE
when you throw brick really close to enemy it splashes jarate

### ISSUE THREAD

**Issue by martyTF** [CreatorsTF/gameservers#33]
bug: when you throw brick really close to enemy it splashes jarate
how to reproduce bug just stand really close to enemy and throw brick, it doesnt have to hit them
specific loadout: brick

reported by viper#522

https://user-images.githubusercontent.com/69526651/135012663-46a3c22a-bc64-43fc-8343-dc0dd4ab85df.mp4

**Comment by sapphonie** [comment]
43cacf450da546db7a9cc22188eb85cc39036b3e
