### ISSUE TITLE
When you have a custom weapon equipped and you touch a resupply cabinet, your active weapon is changed to the custom weapon.

### ISSUE THREAD

**Issue by martyTF** [CreatorsTF/gameservers#5]

**Comment by zonical** [comment]
This is _most likely_ due to tf_persist_item being disabled on a patch to fix MvM crashes if I remember correctly. I'll need to do more specific testing to see if this fixes it as I can't fully remember if it does.

**Comment by nosoop** [comment]
Yes, this would be caused by other plugins re-equipping destroyed items (which is what the persist item plugin is intended to prevent).  A hotfix would be to force the correct slot on change via `Weapon_Switch`, but the timing depends on when C.TF econ applies its items.

**Comment by zonical** [comment]
We're planning to re-enable `tf_persist_item` on our next major patch which isn't too far away. This should hopefully fix this issue and #6.

**Comment by sapphonie** [comment]
Closed in a0f71bb208490e9019756b7810b83833726089d3
