### ISSUE TITLE
When using a Custom weapon that requires charging (Hypodermic Injector, Medigun, etc.), the charge resets when touching a resupply cabinet.

### ISSUE THREAD

**Issue by martyTF** [CreatorsTF/gameservers#6]

**Comment by zonical** [comment]
This is due to tf_persist_item being disabled on a patch to fix MvM crashes if I remember correctly. I've re-enabled this on our closed beta server and from the testing I was apart of, it seemed to work fine.

**Comment by sapphonie** [comment]
Closed: #5
