### ISSUE TITLE
Hypodermic Injector overheals incorrectly vs RED Giant Robots.

### ISSUE THREAD

**Issue by martyTF** [CreatorsTF/gameservers#8]
When using the HI charge against a RED Giant in MvM, you will "heal" to your maximum overheal level of the Giant's Base HP, however that results in often "healing" it down by 2500 HP, as e.g. a Giant Soldier will go from 3000 HP to 300 (which is 150% of a normal Soldier's HP, which this weapon uses as the Giant's Base HP).

**Comment by sapphonie** [comment]
wontfiox as mvm event ends on Sept 1, when this will be closed

**Comment by sapphonie** [comment]
Closed RE: MVM
